apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-11-27T17:44:25Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: namenode
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":9870,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-11-27T17:44:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-11-27T17:45:00Z"
  name: namenode-service
  namespace: default
  resourceVersion: "2299370"
  uid: 98ea80a0-3562-4d71-96c0-6d91555548a9
spec:
  clusterIP: 10.64.13.201
  clusterIPs:
  - 10.64.13.201
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 9870-to-9870-tcp
    nodePort: 32636
    port: 9870
    protocol: TCP
    targetPort: 9870
  - name: 9000-to-9000-tcp
    nodePort: 30075
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: namenode
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.145.202.186
